steps:

- id: "Installing Go App"
  name: "gcr.io/cloud-builders/go"
  args: ["install", "app"]
  env: ["GOPATH=."]

- id: "Running Test"
  name: "gcr.io/cloud-builders/go"
  args: ["test", "app"]
  env: ["GOPATH=."]

- id: "Building image from Dockerfile.prod"
  name: "gcr.io/cloud-builders/docker"
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/app-go-codeedu:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/app-go-codeedu:$SHORT_SHA'
  - '.'
  - '-f'
  - './Dockerfile.prod'

- id: "Pushing image latest"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/app-go-codeedu:latest"]

- id: "Pushing image $SHORT_SHA"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/app-go-codeedu:$SHORT_SHA"]

- id: "Adjusting deployment file -k8s"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go-codeedu:$SHORT_SHA#g' ./k8s/app.yaml > k8s/app-new.yaml;
      cat k8s/app-new.yaml

# - id: "Deploying k8s"
#   name: "gcr.io/cloud-builders/kubectl"
#   args:
#     - 'apply'
#     - '-f'
#     - 'k8s/app-new.yaml'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'